project_name: scaffolding

env:
  - GO111MODULE=on
  - COSIGN_EXPERIMENTAL=true

before:
  hooks:
    - go mod tidy -compat=1.17
    - /bin/bash -c 'if [ -n "$(git --no-pager diff --exit-code go.mod go.sum)" ]; then exit 1; fi'
    - /bin/bash -c 'make release-images'
    - /bin/bash -c 'make sign-images'

builds:
  - skip: true

release:
  prerelease: allow # remove this when we start publishing non-prerelease or set to auto
  draft: true # allow for manual edits
  github:
    owner: sigstore
    name: scaffolding
  footer: |
    ### Thanks to all contributors!
  extra_files:
    - glob: "./release.yaml"
    - glob: "./testrelease.yaml"
    - glob: "./hack/setup-kind.sh"
