defaultBaseImage: ghcr.io/chainguard-dev/apko:v0.2.2

builds:
- id: ctlog
  dir: .
  main: ./cmd/ctlog/createctconfig
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  - -tags
  - nostackdriver
  ldflags:
  - -s
  - -w
  - -extldflags "-static"
  - "{{ .Env.LDFLAGS }}"

- id: fulcio
  dir: .
  main: ./cmd/fulcio/createcerts
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  - -tags
  - nostackdriver
  ldflags:
  - -s
  - -w
  - -extldflags "-static"
  - "{{ .Env.LDFLAGS }}"

- id: rekor
  dir: .
  main: ./cmd/rekor/checktree
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  - -tags
  - nostackdriver
  ldflags:
  - -s
  - -w
  - -extldflags "-static"
  - "{{ .Env.LDFLAGS }}"

- id: trillian
  dir: .
  main: ./cmd/trillian/createtree
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  - -tags
  - nostackdriver
  ldflags:
  - -s
  - -w
  - -extldflags "-static"
  - "{{ .Env.LDFLAGS }}"

- id: getoidctoken
  dir: .
  main: ./cmd/getoidctoken
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  - -tags
  - nostackdriver
  ldflags:
  - -s
  - -w
  - -extldflags "-static"
  - "{{ .Env.LDFLAGS }}"
