# This Dockerfile simply serves as a trigger for dependabot to notify when a new upstream release of a component is available
#
# This will trigger a Dependabot update, which should trigger a workflow to update .ko.yaml accordingly
FROM gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.15.0-alpine@sha256:7815b33cc48745133a065d32b5f420d6b2572565424d90cd8f4261d9529060f2
ENV FOO=BAR
