# This Dockerfile simply serves as a trigger for dependabot to notify when a new upstream release of a component is available
FROM gcr.io/cloud-sql-connectors/cloud-sql-proxy@sha256:b0aee6522475a236254394e573bae95693c02f8a07bceccb110f4e90336a1722 as cloud-sql-proxy
# update references in '.ko.yaml'
ENV FOO=BAR
