---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tsa-system
  name: secret-operator
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["create", "get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-secret-operator
  namespace: tsa-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-operator
subjects:
- kind: ServiceAccount
  name: createsecret
  namespace: tsa-system
