---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: rekor-system
spec:
  ports:
    - port: 6379
  selector:
    app: redis
  clusterIP: None
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: rekor-system
  labels:
    app: redis
spec:
  containers:
    - image: docker.io/redis:5.0.10
      name: redis
      args: [
        "--bind",
        "0.0.0.0",
        "--appendonly",
        "yes"
      ]
      ports:
      - containerPort: 6379
        name: redis
