apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tuf
subjects:
  - kind: ServiceAccount
    name: tuf
    namespace: tuf-system
roleRef:
  kind: ClusterRole
  name: tuf-rbac
  apiGroup: rbac.authorization.k8s.io
