---
apiVersion: batch/v1
kind: Job
metadata:
  name: createsecret
  namespace: rekor-system
spec:
  backoffLimit: 30
  ttlSecondsAfterFinished: 600
  template:
    spec:
      serviceAccountName: createsecret
      restartPolicy: Never
      automountServiceAccountToken: true
      containers:
      - name: createsecret
        image: ko://github.com/sigstore/scaffolding/cmd/rekor/createsecret
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
