name: Create Tink Keyset Test

on:
  pull_request:
    branches:
      - main
    paths:
    - 'tools/create-tink-keyset/cmd/create-tink-keyset/**'

permissions: {}

jobs:
  create-tink-keyset-test:
    name: 'Build Create Tink Keyset'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.work'
          check-latest: true
          cache: false

      - name: Create Tink Keyset build
        id: create-tink-keyset-test
        run: go build ./tools/create-tink-keyset/cmd/create-tink-keyset
