name: Release

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions: {}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      packages: write
      contents: write

    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on

    steps:
    - name: Check out code onto GOPATH
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 1
        path: ./src/github.com/${{ github.repository }}
        persist-credentials: false

    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: ./src/github.com/${{ github.repository }}/go.work
        check-latest: true
        cache: false

    - name: Install ko
      uses: ko-build/setup-ko@61b4d1d396f5b2e7d6bb6fefdce3dc38d1a13445 # v0.10

    - name: Install cosign
      uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
      with:
        install-only: true

    - name: Log into ghcr.io
      uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get TAG
      id: get_tag
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Run goreleaser
      working-directory: ./src/github.com/${{ github.repository }}
      run: goreleaser release --clean --timeout 120m
      env:
        GIT_TAG: ${{ steps.get_tag.outputs.TAG }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
