name: Release

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      packages: write
      contents: write

    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on
      COSIGN_EXPERIMENTAL: "true"

    steps:
    - name: Check out code onto GOPATH
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 1
        path: ./src/github.com/${{ github.repository }}
        persist-credentials: false

    - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version-file: ./src/github.com/${{ github.repository }}/go.work
        check-latest: true

    - name: Install ko
      uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9

    - name: Install cosign
      uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62 # v3.10.0

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
      with:
        install-only: true

    - name: Log into ghcr.io
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get TAG
      id: get_tag
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Run goreleaser
      working-directory: ./src/github.com/${{ github.repository }}
      run: goreleaser release --clean --timeout 120m
      env:
        GIT_TAG: ${{ steps.get_tag.outputs.TAG }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
